### ISSUE TITLE
-sourcemap option working?

### ISSUE THREAD

**Issue by rhukster** [dailymuse/gosass#9]
I'm not getting sourcemaps when i use this option in combination with -watch is there some trick to it?

```
gosass -input scss/ -output css-compiled/ -sourcemap -watch -style compressed
```

Cheers!

**Comment by rhukster** [comment]
BTW:

```
> sassc --version
sassc: 3.3.0
libsass: 3.3.3
sass2scss: 1.0.5
```

**Comment by ysimonson** [comment]
It's a bug. `sassc` apparently does not generate sourcemaps when the css output is send to stdout (makes sense - it wouldn't know where the sass files are relative to the output.) We changed our call to `sassc` to print output to stdout so that the source could be piped to plugins. Even if we saved to a file first, sourcemaps would break when plugins are used anyways, as they can arbitrarily manipulate the source code.

I'm a bit torn on what to do. My current temptation is to just remove plugins all-together, as they're pretty half-baked and cause a ton of problems like this. But I'm not sure if that complicates peoples' workflows (it certainly complicates ours.)

**Comment by ysimonson** [comment]
Could you try using the branch `feature/no-plugins`? It should be addressed there - it appears to be generating sourcemaps for me.

I wouldn't be able to merge this immediately since we're dependent on plugins at the moment, but will see what we can do to get it in ASAP.

**Comment by rhukster** [comment]
I just checked out the feature/no-plugins branch and rebuilt:

```
> cat gosass.sh
#!/bin/sh
gosass -input scss/ -output css-compiled/ -sourcemap -watch -style compressed

> ./gosass.sh
[scss/simple-fonts.scss] Compiled to css-compiled/simple-fonts.css
[scss/fonts.scss] Compiled to css-compiled/fonts.css
[scss/preset.scss] Compiled to css-compiled/preset.css
[scss/template.scss] Compiled to css-compiled/template.css
[scss/nucleus.scss] Compiled to css-compiled/nucleus.css
```

Doesn't seem to be working.  How can i confirm the version is correct? There doesn't seem to be a `-version / -v` option?

**Comment by ysimonson** [comment]
Just to confirm, you checked that folder right? Didn't see any `.map` files in there?

Easiest way to ensure you're using the right version: is there a `-plugins` option when you run `gosass`? If no, you're using the right build.

**Comment by rhukster** [comment]
Doh! the files were there!

I was just going based on the output displaying map files being generated alongside the css like the ruby compiler does.  So yes, it is creating map files!

**Comment by ysimonson** [comment]
Great! Thanks for reporting back.
